project:
  type: website
  output-dir: docs

website:
  title: "STS ST07 Programming in R"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Installation Guidelines"
        href: installation_guidelines.qmd
      - text: "Swirl Guidelines"
        href: swirl_guidelines.qmd
