project:
  type: website
  output-dir: docs

website:
  title: "EDSTS course â€“ Programming in R"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: guidelines.qmd
        text: Guidelines

format:
  html:
    theme: cosmo
    toc: true
